### PR TITLE
Some small changes to aid mingw compilers.

### PR DESCRIPTION
**Pull request by bernhardu**
These changes created either warnings or errors when compiling with mingw.
Except the patch to KeyMap.h, which is just a change in the comment.

These are the first and simpler ones of series in my mingw branch.

### CODE REVIEW

**Comment by Neustradamus** [comment]
@bernhardu; Have you other improvements?

**Comment by Neustradamus** [comment]
@bernhardu: Your last 2 PRs have been merged!
What is your email address?
Can you send me an email here and remove the comment after?

I think that you have other improvements too...

**Comment by bernhardu** [comment]
I have updated this branch a few days ago. It contains other changes that might be interesting to upstream?
https://github.com/bernhardu/UltraVNC/tree/mingw

**Comment by Neustradamus** [comment]
@bernhardu: I think that @RudiDeVos prefers to see PR ^^
But it is good to separate in several PRs.

**Comment by Neustradamus** [comment]
@bernhardu: What is your email address?

**Comment by Neustradamus** [comment]
@bernhardu: What is your email address?
Better to talk!

**Comment by bernhardu** [comment]
> @bernhardu: What is your email address?
> Better to talk!

That sounds like a threat?
My email is contained in nearly each patch that I push to git like [here](https://github.com/ultravnc/UltraVNC/commit/3b15de08fa66a7a0868fe7428c6eec817dd022e6.patch), so I don't understand your request?

**Comment by Neustradamus** [comment]
@bernhardu: You can remove the last comment ^^

**Pull request merged**
