### PR TITLE
UltraVNC Remove of vncproperties.cpp 3 files need to update #225 End

### PR DESCRIPTION
**Pull request by jose94752**
@RudiDeVos UltraVNC Remove of vncproperties.cpp 3 files need to update https://github.com/ultravnc/UltraVNC/issues/225 End

### CODE REVIEW

**Comment by Neustradamus** [comment]
@jose94752: It is not possible to have only one commit with your changes?

**Comment by jose94752** [comment]
@Neustradamus These one 6741989d77954306689ea032c577cddaa3e9b3e8
https://github.com/ultravnc/UltraVNC/commit/6741989d77954306689ea032c577cddaa3e9b3e8
image

**Comment by jose94752** [comment]
@Neustradamus And another for "UltraVNC Remove of vncpropertiesPoll.cpp & vncpropertiesPoll.h 3 files need to update main"
6741989d77954306689ea032c577cddaa3e9b3e8
https://github.com/ultravnc/UltraVNC/commit/6741989d77954306689ea032c577cddaa3e9b3e8
image

**Comment by Neustradamus** [comment]
@jose94752: It is not possible to rebase your PR?

**Comment by jose94752** [comment]
@Neustradamus Rebase in progress
`XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 23/35)
$ git rebase --continue
dropping 562a0cecb68046e99ad4cddb6b18f243c6a4fa5d Fix output directories for custom build step for buildtime.cpp. (#209) -- patch contents already upstream
Auto-merging cmake/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/CMakeLists.txt
Auto-merging cmake/libomnithread/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/libomnithread/CMakeLists.txt
Auto-merging cmake/librdr/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/librdr/CMakeLists.txt
Auto-merging cmake/libudtcloud/CMakeLists.txt
Auto-merging cmake/libzip32/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/libzip32/CMakeLists.txt
Auto-merging cmake/libzipunzip/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/libzipunzip/CMakeLists.txt
Auto-merging cmake/readme.txt
CONFLICT (content): Merge conflict in cmake/readme.txt
Auto-merging cmake/repeater/CMakeLists.txt
CONFLICT (content): Merge conflict in cmake/repeater/CMakeLists.txt
Auto-merging cmake/winvnc/CMakeLists.txt
error: could not apply 6592ed9e... Update cmake some more. (#208)
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config advice.mergeConflict false"
Could not apply 6592ed9e... Update cmake some more. (#208)

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 25/35)
`

**Comment by jose94752** [comment]
End of my git rebase.
`[...]
XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 35/35)
$ git rebase --continue
error: update_ref failed for ref 'refs/heads/main': cannot lock ref 'refs/heads/main': is at c9ea19657fc3c136e39a17081879880bc804ef92 but expected 6741989d77954306689ea032c577cddaa3e9b3e8
error: could not update refs/heads/main

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 35/35)
$ git merge upstream/main
Already up to date.

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 35/35)
$ git push -f origin main
Enumerating objects: 189, done.
Counting objects: 100% (189/189), done.
Delta compression using up to 12 threads
Compressing objects: 100% (146/146), done.
Writing objects: 100% (168/168), 173.69 KiB | 5.26 MiB/s, done.
Total 168 (delta 70), reused 51 (delta 14), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (70/70), completed with 14 local objects.
To https://github.com/jose94752/UltraVNC.git
   6741989d..c9ea1965  main -> main

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main|REBASE 35/35)
$ rm -fr ".git/rebase-merge"

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main)
$ git pull
Already up to date.

XXXX@YYYYYYY MINGW64 /c/source/UltraVNC (main)
$ git push
Everything up-to-date`

**Comment by Neustradamus** [comment]
@jose94752: The goal is to have only your commits, not others, currently there are 53 :/

**Comment by jose94752** [comment]
@Neustradamus I rebase again without of the mistake to commit changes (adding, removing, ,...) with "git commit" on the "git rebase --continue" which it's calling herself commit if he needs. Nevertheless, I have 29 commits ahead.

**Comment by Neustradamus** [comment]
@jose94752: Please save your changes and can you look to do:
- https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a

**Comment by jose94752** [comment]
@Neustradamus I have again doing these yesterday may be the changes are good, if they not I will directly make them on another computer on the original repository.

**Review by corfeyj — APPROVED** [review]

**Review by corfeyj — APPROVED** [review]

**Review by corfeyj — APPROVED** [review]

**Comment by jose94752** [comment]
winvnc/winvnc/winvnc.vcxproj
winvnc/winvnc/winvnc.vcxproj.filters
Need to revert changes, I will doing these.

**Comment by RudiDeVos** [comment]
Is this PR OK to merge ?

**Comment by jose94752** [comment]
@RudiDeVos I will add your 2 lasts behind changes but 31 commits ahead are need to check.
image

**Comment by jose94752** [comment]
@RudiDeVos May be now is good
image

**Comment by Neustradamus** [comment]
@jose94752: Please keep your changes in a different folder.

From https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a
```
git remote add upstream https://github.com/ultravnc/UltraVNC.git
git fetch upstream
git rebase upstream/master
```

Normally you will have now, the same than current upstream and create one commit with you changes.

**Comment by Neustradamus** [comment]
@jose94752: Can you add me full-right on your fork?
I will solve it.

Important: Please save your code in your computer.

**Comment by jose94752** [comment]
@Neustradamus `jpluq@Reine-des-Neiges MINGW64 /c/source/UltraVNC (main)
$ git branch -D mainTemp
Deleted branch mainTemp (was c9ea1965).

XXXX@YYYY MINGW64 /c/source/UltraVNC (main)
$ git branch
  QtCommunityTests
  list
* main
  ultravnc-main

XXXX@YYYY MINGW64 /c/source/UltraVNC (main)
$ git branch QtMain

XXXX@YYYY MINGW64 /c/source/UltraVNC (main)
$ git checkout QtMain
Switched to branch 'QtMain'

XXXX@YYYY MINGW64 /c/source/UltraVNC (QtMain)
$
` What should I'm doing next delete the main branch on my computer and clone ? ... I prefer to send you full-right on my fork

**Comment by Neustradamus** [comment]
@jose94752: I have resetted correctly but the PR has been closed at the same time, can you add a new commit with your changes based on upstream?
Can you remove all your comments to reduce the message here too? I have already removed a lot of mine...

**Comment by jose94752** [comment]
@Neustradamus I have reduced here my comments upper, and I will be doing next time over the code when I will recover my Internet fiber connection which is down. My ISP saying by SMS the October 21, 2024 22:00. I use actually my smartphone with a 50 GB of Data over 4G give by ISP, if necessary to doing quick the remove of unnecessary comments.

**Pull request closed without merging**
