### PR TITLE
WIP: RSA-AES authentication and encryption

### PR DESCRIPTION
**Pull request by wqweto**
Work in progress, do not merge! 

This is an implementation of RSA key exchange and AES in EAX mode largely modeled after [CSecurityRSAAES](https://github.com/TigerVNC/tigervnc/blob/986280b382d57ef4f68d2d4afb13b26772e5acb0/common/rfb/CSecurityRSAAES.cxx) from TigerVNC but there is no external dependency because it's using standard Crypto API for KEX and AES.

I'm testing this against wayvnc (v0.8-dev-d819ca4) on Ubuntu and successfully performed auth incl. encr/decryption of last messages with handshake hash and user/password.

Unfortunately I'm not quite sure how can this be further integrated with current architecture of the viewer. Tried to implement `IPlugin` interface and hacked some `m_pPluginInterface` availability checks in ClientConnection but ultimately viewer is failing after logon with "WriteExact: DSMPlugin-RestoreBuffer Error" as there is no `m_pDSMPlugin` initialized but only `m_pPluginInterface`.

Will keep on hacking, all pointers welcome.

### CODE REVIEW

**Comment by RudiDeVos** [comment]
Looks interesting,
Will take a look after 01/28

**Comment by wqweto** [comment]
This latest commit received first correct frame buffer using ZRLE encoding

image

Unfortunately RAW and most other encodings still don't work incl. ZRLE with `Use Cache Encoding` option set. Will need further debugging.

**Comment by wqweto** [comment]
- RAW and Tight encodings are now working with wayvnc
- The `Use Cache Encoding` weirdness turned out to be a [bug in wayvnc](https://github.com/any1/neatvnc/issues/108) apparently

This PR is ready for review unless there are more issues and other regressions found.

**Comment by wqweto** [comment]
I'm wondering how to implement server fingerprint confirmation.

Currently `VerifyServer` function just logs the calculated fingerprint and accept the server identity is ok (no MITM assumed) but in TigerVNC they ask for manual fingerprint confirmation each time the connection is established

image

In contrast to TigerVNC in openssh/putty the confirmation of fingerprint mapping to server name is persisted (in registry) so on subsequent connection this message box is skipped.

This will probably need further work in terms of UI and choice persistence as I'll just leave it with logged text only for now.

**Comment by wqweto** [comment]
Btw, I just made considerable progress on my [`vencrypt`](https://github.com/wqweto/UltraVNC/compare/rsa-aes...wqweto:UltraVNC:vencrypt?expand=1) branch with VeNCrypt authentication with TLS encrypted transport based on Windows built-in Schannel API (incl. TLS 1.3 on Win11) . The working implementation is ~600 LOC with ready support for `TLSNone`, `TLSPlain`, `X509None` and `X509Plain` sub-types.

I'll wait for this PR to get sorted out and eventually merged before submitting a rebased PR of the next branch.

**Comment by Neustradamus** [comment]
@wqweto: Really nice job! :)

**Comment by Neustradamus** [comment]
@wqweto: I have sent you an email, please answer me by email ^^

Thanks in advance.

**Comment by Neustradamus** [comment]
@wqweto: I have sent you an email, please answer me by email.

Thanks in advance.

**Comment by RudiDeVos** [comment]
Back from holidays, 
Code looks interesting,  further then my own playground code, was still fighting on the encrypt/decrypt part
Will try to build it and test it

**Comment by wqweto** [comment]
In ce34adc63b69d8794c879193c9dbeb57958f8aae a kind of fingerprint persistence is added with a checkbox on confirmation task dialog

image

. . . which when checked saves fingerprint in `options.vnc` file keyed on `server:port` pair like this

```
[connection]
H=172.17.17.159
index=HGFBEDCA
[fingerprint]
172.17.17.159:5900=47-49-b2-13-ca-8e-96-9d
```
This is one possible implementation of key fingerprint persistence which should probably be fine-tuned.

**Comment by RudiDeVos** [comment]
I'm trying to get it work with RA2ne ( only password is encrypted).
(vncserver -securitytypes RA2ne -xstartup /usr/bin/xterm -localhost no -verbose)
Aftser sending passwd is see 
Server default pixel format depth....
But never get the auth result back.

Still testing

**Comment by RudiDeVos** [comment]
This seems to work ( i'm getting auth ok, but no image)
void ClientConnection::AuthRSAAES(int keySize, bool encrypted)
{
	TCHAR key[MAX_HOST_NAME_LEN];
	sprintf_s(key, "%s:%d", m_host, m_port);
	KEXHost host(this, key, m_opts->getDefaultOptionsFileName());
	RSAKEX st(host, (DWORD)keySize);
	if (!st.ReadPublicKey()
		|| !st.VerifyServer() 
		|| !st.WritePublicKey()
		|| !st.WriteRandom()
		|| !st.ReadRandom()
		|| !st.SetCipher(m_fUsePlugin, &m_pPluginInterface)
		|| !st.WriteHash()
		|| !st.ReadHash()
		|| !st.ReadSubtype()
		|| !st.WriteCredentials(m_host, m_port, m_cmdlnUser, m_clearPasswd)) {
		if (strlen(st.lastError))
		{
			vnclog.Print(0, _T("AuthRSAAES: %s\n"), st.lastError);
			throw WarningException(st.lastError);
		}
	}
	if (!encrypted)
	{
		if (m_pPluginInterface)
			delete m_pPluginInterface;
		m_pPluginInterface = NULL;
		m_pIntegratedPluginInterface = NULL;
	}

}
Use plugin for auth and disable after

**Comment by wqweto** [comment]
Yes, I just committed a fix for this issue.

It turned out non-encrypting sub-types (RA2ne and RA2ne_256) actually do encrypt the second part of the handshake so you cannot implement RA2ne without implementing AES in EAX mode alas. Also this means that vncserver must have `RSAKey` parameter set to a valid private key or it will immediately close client connection on handshake if key file is missing.

Also I had to backport a fix to `FdInStream` class from my `vencrypt` branch -- it had a bug where encrypted data was lost on `SetReadFromMemoryBuffer` call which dropped client connection halfway displaying screenbuffer (works with wayvnc though).

I'm testing RSA-AES impl on Ubuntu with TigerVNC build from sources and will continue testing with VeNCrypt authentication and TLS.

Here is my cheat-sheet for setting up the VNC server on Ubuntu 20.04 so far

Private key generation for RSA-AES:
```
$ ssh-keygen -m pem -f ~/rsa_key.pem -t rsa -N ""
```
Need to first create password for VNC authentication
```
$ vncpasswd
```
Need to notice current display index in list of available X11 displays e.g. `:10` or `:2`
```
$ xauth list
```
Running VNC server for current display from above
```
$ x0vncserver -passwordfile ~/.vnc/passwd -display :10 -SecurityTypes RA2ne -RSAKey ~/rsa_key.pem
```
Stop VNC server
```
Ctrl+\: mercilessly kill the process that is currently in the foreground
```

**Comment by RudiDeVos** [comment]
Tigervnc also has the auto generate pem options then you don't need to pre generate and add the -RSAKey option
Testing...

**Comment by RudiDeVos** [comment]
Confirm, code is working with -SecurityTypes RA2ne

**Comment by wqweto** [comment]
> Tigervnc also has the auto generate pem options then you don't need to pre generate and add the -RSAKey option
> Testing...

This seems logical provided that this PR generates different 2048-bit client RSA key on each handshake i.e. it’s not very CPU intensive.

**Comment by Neustradamus** [comment]
@wqweto: Excellent, @RudiDeVos has already merged :)

Good job @wqweto for this important contribution!

**Comment by Neustradamus** [comment]
@wqweto: Your good improvements are now in the new stable version: UltraVNC 1.6.0.0 :)

**Pull request merged**
